export const ANSWER_GET = 'ANSWER_GET';
export const ANSWER_GET_ONE = 'ANSWER_GET_ONE';
export const ANSWER_GET_MULTIPLE = 'ANSWER_GET_MULTIPLE';
export const ANSWER_LOADING = 'ANSWER_LOADING';
export const ANSWER_LOADING_ERROR = 'ANSWER_LOADING_ERROR';