export const DISTRACTOR_GET = 'DISTRACTOR_GET';
export const DISTRACTOR_GET_ONE = 'DISTRACTOR_GET_ONE';
export const DISTRACTOR_GET_MULTIPLE = 'DISTRACTOR_GET_MULTIPLE';
export const DISTRACTOR_LOADING = 'DISTRACTOR_LOADING';
export const DISTRACTOR_LOADING_ERROR = 'DISTRACTOR_LOADING_ERROR';