export const INSTRUCTION_GET = 'INSTRUCTION_GET';
export const INSTRUCTION_GET_ONE = 'INSTRUCTION_GET_ONE';
export const INSTRUCTION_GET_MULTIPLE = 'INSTRUCTION_GET_MULTIPLE';
export const INSTRUCTION_LOADING = 'INSTRUCTION_LOADING';
export const INSTRUCTION_LOADING_ERROR = 'INSTRUCTION_LOADING_ERROR';