export const MOCK_GET_ONE = 'MOCK_GET_ONE';
export const MOCK_GET_MULTIPLE = 'MOCK_GET_MULTIPLE';
export const MOCK_GET_SELECTED = 'MOCK_GET_SELECTED';
export const MOCK_LOADING = 'MOCK_LOADING';
export const MOCK_LOADING_ERROR = 'MOCK_LOADING_ERROR';
export const MOCK_DOWNLOADING = 'MOCK_DOWNLOADING';
export const MOCK_DOWNLOADING_SUCCESS = 'MOCK_DOWNLOADING_SUCCESS';
export const MOCK_DOWNLOADING_FAIL = 'MOCK_DOWNLOADING_FAIL';
