export const QUESTION_GET = 'QUESTION_GET';
export const QUESTION_GET_ONE = 'QUESTION_GET_ONE';
export const QUESTION_GET_MULTIPLE = 'QUESTION_GET_MULTIPLE';
export const QUESTION_LOADING = 'QUESTION_LOADING';
export const QUESTION_LOADING_ERROR = 'QUESTION_LOADING_ERROR';