export const RESOURCE_GET_ONE = 'RESOURCE_GET_ONE';
export const RESOURCE_GET_MULTIPLE = 'RESOURCE_GET_MULTIPLE';
export const RESOURCE_GET_SELECTED = 'RESOURCE_GET_SELECTED';
export const RESOURCE_LOADING = 'RESOURCE_LOADING';
export const RESOURCE_LOADING_ERROR = 'RESOURCE_LOADING_ERROR';
export const RESOURCE_DOWNLOADING = 'RESOURCE_DOWNLOADING';
export const RESOURCE_DOWNLOADING_SUCCESS = 'RESOURCE_DOWNLOADING_SUCCESS';
export const RESOURCE_DOWNLOADING_FAIL = 'RESOURCE_DOWNLOADING_FAIL';
