export const SUBJECT_GET_ONE = 'SUBJECT_GET_ONE';
export const SUBJECT_GET_MULTIPLE = 'SUBJECT_GET_MULTIPLE';
export const SUBJECT_LOADING = 'SUBJECT_LOADING';
export const SUBJECT_LOADING_ERROR = 'SUBJECT_LOADING_ERROR';
export const SUBJECT_DOWNLOADING = 'SUBJECT_DOWNLOADING';
export const SUBJECT_DOWNLOADING_SUCCESS = 'SUBJECT_DOWNLOADING_SUCCESS';
export const SUBJECT_DOWNLOADING_FAIL = 'SUBJECT_DOWNLOADING_FAIL';
