export const SUBJECT_GET_ONE = 'SUBJECT_GET_ONE';
export const SUBJECT_GET_MULTIPLE = 'SUBJECT_GET_MULTIPLE';
export const SUBJECT_LOADING = 'SUBJECT_LOADING';
export const SUBJECT_LOADING_ERROR = 'SUBJECT_LOADING_ERROR';
export const SUBJECT_GET_MULTIPLE_ONLINE = 'SUBJECT_GET_MULTIPLE_ONLINE';
export const SUBJECT_LOADING_ONLINE = 'SUBJECT_LOADING_ONLINE';
export const SUBJECT_LOADING_ONLINE_ERROR = 'SUBJECT_LOADING_ONLINE_ERROR';
