export const THEME_GET_ONE = 'THEME_GET_ONE';
export const THEME_GET_MULTIPLE = 'THEME_GET_MULTIPLE';
export const THEME_GET_SELECTED = 'THEME_GET_SELECTED';
export const THEME_LOADING = 'THEME_LOADING';
export const THEME_LOADING_ERROR = 'THEME_LOADING_ERROR';
export const THEME_DOWNLOADING = 'THEME_DOWNLOADING';
export const THEME_DOWNLOADING_SUCCESS = 'THEME_DOWNLOADING_SUCCESS';
export const THEME_DOWNLOADING_FAIL = 'THEME_DOWNLOADING_FAIL';
