export const THEME_GET = 'THEME_GET';
export const THEME_GET_ONE = 'THEME_GET_ONE';
export const THEME_GET_MULTIPLE = 'THEME_GET_MULTIPLE';
export const THEME_LOADING = 'THEME_LOADING';
export const THEME_LOADING_ERROR = 'THEME_LOADING_ERROR';