export const THEME_GET_ONE = 'THEME_GET_ONE';
export const THEME_GET_MULTIPLE = 'THEME_GET_MULTIPLE';
export const THEME_LOADING = 'THEME_LOADING';
export const THEME_LOADING_ERROR = 'THEME_LOADING_ERROR';
export const THEME_GET_MULTIPLE_ONLINE = 'THEME_GET_MULTIPLE_ONLINE';
export const THEME_LOADING_ONLINE = 'THEME_LOADING_ONLINE';
export const THEME_LOADING_ONLINE_ERROR = 'THEME_LOADING_ONLINE_ERROR';
export const THEME_GET_SELECTED = 'THEME_GET_SELECTED';
