export const TOPIC_GET_ONE = 'TOPIC_GET_ONE';
export const TOPIC_GET_MULTIPLE = 'TOPIC_GET_MULTIPLE';
export const TOPIC_LOADING = 'TOPIC_LOADING';
export const TOPIC_LOADING_ERROR = 'TOPIC_LOADING_ERROR';
export const TOPIC_GET_MULTIPLE_ONLINE = 'TOPIC_GET_MULTIPLE_ONLINE';
export const TOPIC_LOADING_ONLINE = 'TOPIC_LOADING_ONLINE';
export const TOPIC_LOADING_ONLINE_ERROR = 'TOPIC_LOADING_ONLINE_ERROR';
export const TOPIC_GET_SELECTED = 'TOPIC_GET_SELECTED';
