export const TOPIC_GET = 'TOPIC_GET';
export const TOPIC_GET_ONE = 'TOPIC_GET_ONE';
export const TOPIC_GET_MULTIPLE = 'TOPIC_GET_MULTIPLE';
export const TOPIC_LOADING = 'TOPIC_LOADING';
export const TOPIC_LOADING_ERROR = 'TOPIC_LOADING_ERROR';
export const TOPIC_GET_QUESTIONS = 'TOPIC_GET_QUESTIONS';
export const TOPIC_GET_ID = 'TOPIC_GET_ID';